name: Notify in Slack Channels
on: workflow_dispatch
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    name: A job to notify in slack with my github actions
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack Test Result
        uses: sanjaykrishnanrs/slack-notify-junitxml-action@0.1.4-alpha
        with:
          slackbotid: ${{ secrets.slackbotid }}
          slackbottoken: ${{ secrets.slackbottoken }}
          slackchannel: ${{ secrets.slackchannel }}
          junitxml_filepath: WeatherBot/junitreport.xml
