name: Notify in Slack Channels
on: [push,workflow_dispatch]
jobs:
  build:
    name: Build & Integrate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build the code"
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: "Test code"
        run: echo "Test the code"
      - name: "Generate junitreport"
        run: echo "Generate junitreport"
  notify-slack:
    strategy:
      matrix: 
        filename: [ubuntu-latest, windows-latest, macos-latest]
    name: Notify Slack-${{matrix.filename}}
    needs: test
    runs-on: ubuntu-latest
    environment: Slackbot Notification
    steps:
      - uses: actions/checkout@v2
      - name: CI Test Result in Slack
        uses: sanjaykrishnanrs/slack-notify-junitxml-action@0.1.0-beta
        with:
          title: WeatherBot Tests
          slackbotid: ${{ secrets.SLACKBOTID }}
          slackbottoken: ${{ secrets.SLACKBOTTOKEN }}
          slackchannel: ${{ secrets.SLACKCHANNEL }}
          junitxml_filepath: tests/${{matrix.filename}}/junitreport.xml
  
