name: Notify in Slack Channels
on: workflow_dispatch
jobs:
  build:
    name: Build & Integrate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build the code"
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - run: echo "Test the code"
  notify-slack:
    name: Notify Slack
    needs: test
    runs-on: ubuntu-latest
    environment: Slackbot Notification
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack Test Result
        uses: sanjaykrishnanrs/slack-notify-junitxml-action@0.1.12-alpha
        with:
          title: WeatherBot Tests
          slackbotid: ${{ secrets.SLACKBOTID }}
          slackbottoken: ${{ secrets.SLACKBOTTOKEN }}
          slackchannel: ${{ secrets.SLACKCHANNEL }}
          junitxml_filepath: junitreport.xml
  
